// Type definitions for @jsamuel1/pptxgenjs/utils/parse
// Tree-shakeable subset of the /utils barrel — HTML structural recognisers + HTML DOM.
// Re-exported from ./utils (single source of truth) to guarantee parity with the barrel.
export {
	parseSvg,
	parseCards,
	parseHtml,
	query,
	queryOne,
	closest,
	matches,
	isAncestorOrSelf,
	textOf,
	innerTextOf,
	attr,
	clone,
	outerHtml,
	decodeEntities,
	parseTable,
	parseColumns,
	parseTimeline,
	parseQuote,
	parseBadges,
	parseCallout,
	parseTiles,
	parseImages,
} from './utils'
export type {
	SvgPart,
	ParseSvgOptions,
	GradientStop,
	GradientFillProps,
	CardData,
	ParseCardsOptions,
	HNode,
	TableData,
	TableCell,
	ColumnData,
	TimelineRow,
	QuoteData,
	BadgeData,
	CalloutData,
	TileData,
	ParseContentOptions,
	ImageNode,
	ParseImageOptions,
} from './utils'
